### ISSUE TITLE
Clean up tags

### ISSUE THREAD

**Issue by toptobes** [datastaxdevs/gallery_content_loader#2]
Tags should be cleaned up to prevent over-spam and limit tags with just a single result if it's not truly unqiue

Ex. `javascript -> JS`, `building-sample-apps -> tutorial`, `cassandra-database/cassandra-cql -> cassandra`, etc.

Use your best judgement ofc, just try to keep things uniform and necessary

Also make sure tags are uniform in using either dashes or spaces

**Comment by synedra** [comment]
This is done, let me know if there are any issues remaining
