### ISSUE TITLE
Normalize walkthrough times

### ISSUE THREAD

**Issue by toptobes** [datastaxdevs/gallery_content_loader#6]
![image](https://github.com/datastaxdevs/gallery_content_loader/assets/96998732/8e6c2c45-33a3-4ae4-8cca-7b2546683184)

Turn stats like `20m` or `2h` into `20 minutes` and `2 hours`

**Comment by synedra** [comment]
While I can massage the data, I think it'll be better to simply update the astrajson files, so that's what I'll do.

**Comment by synedra** [comment]
This is done, and I'm working on the sample application template with guidance so folks use the right terminology
